### PR TITLE
Render State Notation Parser: Add default section (close #79, close #77)

### LINKED ISSUE #77: Render state parser crashes if PipelineType is not specified
If PipelineType parameter is not specified in a json file, the parser crashes.

The parser must never crash if json file is invalid. It should print the error and exit gracefully.

Besides, PipelineType may be automatically deduced from other members of the filed: if there is a GraphicsPipeline member, pVS, pPS, etc. - the pipeline type is clearly graphics.
Similar with compute and ray tracing pipeline.

This must be covered in tests.

### LINKED ISSUE #79: RenderStateNotationParser: add defaults section
Add "Defaults" section to the json file where default values can be specified:

```json
"Defaults": {
  "Shader" : {
      "SourceLanguage": "HLSL",
      "UseCombinedTextureSamplers": true
  }, 

  "Pipeline":{
  }
},

"Shaders": {

},

"Pipelines" : {
 "GraphicsPipeline": {
        "PrimitiveTopology": "TRIANGLE_LIST"
  }
}
```

This will be very helpful to avoid specifying the same states multiple times, [e.g.](https://github.com/DiligentGraphics/DiligentSamples/blob/render_state_notation/Samples/GLTFViewer/assets/shaders/States.json#L11-L12)

### PR DESCRIPTION
**Pull request by MikhailGorobets**

### CODE REVIEW

File: RenderStateNotationParser/src/RenderStateNotationParserImpl.cpp [hunk 1]
```diff
@@ -302,43 +305,126 @@ RenderStateNotationParserImpl::RenderStateNotationParserImpl(IReferenceCounters*
...
+
 
             for (auto const& Pipeline : Json["Pipelines"])
             {
-                auto& PipelineType = Pipeline.at("PSODesc").at("PipelineType");
+                auto AssignPipelineState = [](PipelineStateNotation& RHS, PipelineStateNotation& LHS, PIPELINE_TYPE Type) {
+                    RHS.PSODesc                     = LHS.PSODesc;
+                    RHS.Flags                       = LHS.Flags;
+                    RHS.ResourceSignaturesNameCount = LHS.ResourceSignaturesNameCount;
+                    RHS.ppResourceSignatureNames    = LHS.ppResourceSignatureNames;
```
Comment (TheMostDiligent) [inline RenderStateNotationParser/src/RenderStateNotationParserImpl.cpp:415]: Why assign one-by-one? `RHS = LHS` is shorter and safer (in case new members are added to the `PipelineStateNotation`)

Comment (TheMostDiligent) [reply RenderStateNotationParser/src/RenderStateNotationParserImpl.cpp:415]: Besides, RHS and LHS are mixed up.

Comment (TheMostDiligent) [reply RenderStateNotationParser/src/RenderStateNotationParserImpl.cpp:415]: Source should be `const &`

File: Tests/DiligentToolsTest/src/RenderStateNotationParser/RenderStateNotationParserTest.cpp [hunk 2]
```diff
@@ -283,6 +283,192 @@ TEST(Tools_RenderStateNotationParser, InlinePipelineStatesTest)
...
 }
 
+TEST(Tools_RenderStateNotationParser, ImplicitPipelineStatesTest)
+{
+    RefCntAutoPtr<IRenderStateNotationParser> pParser = LoadFromFile("ImplicitPipelineStates.json");
+    ASSERT_NE(pParser, nullptr);
+
+    {
+        auto pDesc = pParser->GetGraphicsPipelineStateByName("Graphics-TestName");
+        ASSERT_NE(pDesc, nullptr);
```
Comment (TheMostDiligent) [inline Tests/DiligentToolsTest/src/RenderStateNotationParser/RenderStateNotationParserTest.cpp:293]: Should you also check that the pipeline type is correct?

**Review by TheMostDiligent — CHANGES_REQUESTED** [review]
What about default resource signatures?

**Comment by MikhailGorobets** [comment]
> What about default resource signatures?
Added a feature

File: RenderStateNotationParser/src/RenderStateNotationParserImpl.cpp [hunk 3]
```diff
@@ -188,6 +189,72 @@ void Deserialize(const nlohmann::json& Json, RayTracingPipelineNotation& Type, D
...
+        case Diligent::SHADER_TYPE_RAY_INTERSECTION:
+            return "RAY_INTERSECTION";
+        case Diligent::SHADER_TYPE_TILE:
+            return "TILE";
+        default:
+            UNEXPECTED("Unexpected shader type");
+            return "UNKNOWN";
+    }
+}
+
```
Comment (TheMostDiligent) [inline RenderStateNotationParser/src/RenderStateNotationParserImpl.cpp:257]: There is a `GetShaderTypeLiteralName()` function in GraphicsAccessories.hpp

File: Tests/DiligentToolsTest/src/RenderStateNotationParser/RenderStateNotationParserTest.cpp [hunk 4]
```diff
@@ -283,6 +283,257 @@ TEST(Tools_RenderStateNotationParser, InlinePipelineStatesTest)
...
+    {
+        GraphicsPipelineNotation PipelineReference{};
+        PipelineReference.PSODesc.PipelineType = PIPELINE_TYPE_GRAPHICS;
+        PipelineReference.PSODesc.Name         = "Graphics-TestName";
+        PipelineReference.pVSName              = "Shader0-VS";
+        PipelineReference.pPSName              = "Shader0-PS";
+
+        auto pPipeline = pParser->GetGraphicsPipelineStateByName(PipelineReference.PSODesc.Name);
+        ASSERT_NE(pPipeline, nullptr);
+        ASSERT_EQ(*pPipeline, PipelineReference);
```
Comment (TheMostDiligent) [inline Tests/DiligentToolsTest/src/RenderStateNotationParser/RenderStateNotationParserTest.cpp:300]: There are ASSERT_ and EXPECT_ macros in gtest.
ASSERT_ is for critical checks (e.g. null pointers.) They abort the test.
EXPECT_ is for non-critical checks (e.g. value does not match expected). They do not abort the test and it continues running

**Review by TheMostDiligent — APPROVED** [review]
